import type { Product, Manufacturer } from './types';

export const manufacturers: Manufacturer[] = [
  {
    id: 'm1',
    name: 'Heritage Weaves',
    ownerName: 'Shri Ramchandra Deshmukh',
    location: 'Nashik, Maharashtra',
    years: 45,
    rating: 4.9,
    reviews: 312,
    products: 87,
    followers: 4820,
    responseTime: '< 2 hours',
    priceRange: '₹35,000 – ₹1,50,000',
    verified: true,
    speciality: 'Peacock Motif, Asawali Paithani',
    avatar: 'https://images.unsplash.com/photo-1664636124899-4a121f1ce449?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1569909115134-a0426936c879?w=1200&h=400&fit=crop&auto=format',
    about: 'Established in 1979, Heritage Weaves is a family-run atelier in Nashik specialising in traditional Paithani with natural silk and zari. Three generations of master weavers carry the legacy.',
  },
  {
    id: 'm2',
    name: 'Royal Paithani House',
    ownerName: 'Smt. Vaishali Kulkarni',
    location: 'Paithan, Aurangabad',
    years: 72,
    rating: 5.0,
    reviews: 541,
    products: 143,
    followers: 9210,
    responseTime: '< 1 hour',
    priceRange: '₹50,000 – ₹3,00,000',
    verified: true,
    speciality: 'Heirloom Bridal, Maharani Collections',
    avatar: 'https://images.unsplash.com/photo-1664636126154-7a6ce64edd21?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=1200&h=400&fit=crop&auto=format',
    about: 'Founded in 1952 in the historic town of Paithan — birthplace of Paithani — Royal Paithani House is among the oldest and most distinguished manufacturers, holding GI certification.',
  },
  {
    id: 'm3',
    name: 'Maharashtra Looms',
    ownerName: 'Shri Suresh Patil',
    location: 'Yeola, Nashik',
    years: 38,
    rating: 4.8,
    reviews: 228,
    products: 64,
    followers: 3100,
    responseTime: '< 3 hours',
    priceRange: '₹25,000 – ₹90,000',
    verified: true,
    speciality: 'Munia & Bangadi-Mor Motifs',
    avatar: 'https://images.unsplash.com/photo-1705164454907-a04fe248f675?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1588140686379-1b76a52103dc?w=1200&h=400&fit=crop&auto=format',
    about: 'A Yeola-based cooperative of 40+ skilled weavers known for their vibrant Munia (parrot) motif Paithanis and their meticulous double-weft weaving technique.',
  },
  {
    id: 'm4',
    name: 'Peacock Weavers',
    ownerName: 'Shri Prashant Gaikwad',
    location: 'Aurangabad, Maharashtra',
    years: 25,
    rating: 4.7,
    reviews: 189,
    products: 52,
    followers: 2740,
    responseTime: '< 4 hours',
    priceRange: '₹28,000 – ₹75,000',
    verified: true,
    speciality: 'Contemporary Peacock Designs',
    avatar: 'https://images.unsplash.com/photo-1739429942851-9083ee185d3d?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1569909115134-a0426936c879?w=1200&h=400&fit=crop&auto=format',
    about: 'A newer atelier blending traditional Paithani craft with contemporary colour palettes. Known for bold peacock-eye borders and innovative Paithani-fusion designs.',
  },
  {
    id: 'm5',
    name: 'Devgiri Textiles',
    ownerName: 'Smt. Anuradha Shinde',
    location: 'Aurangabad, Maharashtra',
    years: 55,
    rating: 4.9,
    reviews: 405,
    products: 118,
    followers: 6300,
    responseTime: '< 2 hours',
    priceRange: '₹40,000 – ₹2,00,000',
    verified: true,
    speciality: 'Pure Silk Zari, Wedding Collections',
    avatar: 'https://images.unsplash.com/photo-1618901185975-d59f7091bcfe?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1610189012906-4c0aa9b9781e?w=1200&h=400&fit=crop&auto=format',
    about: 'Named after the historic fort of Devgiri, this matriarch-led house produces exquisite pure-silk Paithanis with real gold and silver zari, beloved by brides across India.',
  },
  {
    id: 'm6',
    name: 'Yeola Silk House',
    ownerName: 'Shri Balkrishna More',
    location: 'Yeola, Nashik',
    years: 30,
    rating: 4.8,
    reviews: 176,
    products: 71,
    followers: 3850,
    responseTime: '< 3 hours',
    priceRange: '₹30,000 – ₹1,20,000',
    verified: true,
    speciality: 'Triveni & Kalicharan Motifs',
    avatar: 'https://images.unsplash.com/photo-1664636125274-743c470f62e6?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1588140686379-1b76a52103dc?w=1200&h=400&fit=crop&auto=format',
    about: 'Yeola Silk House is celebrated for its rare Triveni (three-thread) weave and meticulous handwork. Their sarees are considered heirlooms, often passed across generations.',
  },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Royal Peacock Paithani',
    brand: 'Heritage Weaves',
    manufacturer: 'Shri Ramchandra Deshmukh',
    manufacturerId: 'm1',
    price: 48500,
    rating: 4.9,
    reviews: 87,
    material: 'Pure Mulberry Silk, Real Zari',
    motif: 'Peacock (Mor)',
    color: 'Deep Purple & Emerald',
    location: 'Nashik',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&h=800&fit=crop&auto=format',
    badge: 'Best Seller',
    collection: 'Royal Collection',
  },
  {
    id: 'p2',
    name: 'Bridal Maharani Paithani',
    brand: 'Royal Paithani House',
    manufacturer: 'Smt. Vaishali Kulkarni',
    manufacturerId: 'm2',
    price: 1250000,
    rating: 5.0,
    reviews: 43,
    material: 'Pure Silk, 22K Gold Zari',
    motif: 'Asawali (Flowering Vine)',
    color: 'Crimson & Antique Gold',
    location: 'Paithan',
    image: 'https://images.unsplash.com/photo-1705164454907-a04fe248f675?w=600&h=800&fit=crop&auto=format',
    badge: 'Heirloom',
    collection: 'Bridal Paithani',
  },
  {
    id: 'p3',
    name: 'Munia Paithani',
    brand: 'Maharashtra Looms',
    manufacturer: 'Shri Suresh Patil',
    manufacturerId: 'm3',
    price: 34500,
    rating: 4.8,
    reviews: 112,
    material: 'Art Silk with Real Zari',
    motif: 'Munia (Parrot)',
    color: 'Peacock Blue & Gold',
    location: 'Yeola',
    image: 'https://images.unsplash.com/photo-1610189012906-4c0aa9b9781e?w=600&h=800&fit=crop&auto=format',
    badge: 'New Arrival',
    collection: 'New Arrivals',
  },
  {
    id: 'p4',
    name: 'Heritage Bangadi-Mor',
    brand: 'Devgiri Textiles',
    manufacturer: 'Smt. Anuradha Shinde',
    manufacturerId: 'm5',
    price: 89000,
    rating: 4.9,
    reviews: 65,
    material: 'Pure Mulberry Silk, Silver Zari',
    motif: 'Bangadi-Mor (Bangle Peacock)',
    color: 'Emerald & Burgundy',
    location: 'Aurangabad',
    image: 'https://images.unsplash.com/photo-1739429942851-9083ee185d3d?w=600&h=800&fit=crop&auto=format',
    badge: 'Heritage Pick',
    collection: 'Heritage Collection',
  },
  {
    id: 'p5',
    name: 'Contemporary Peacock Paithani',
    brand: 'Peacock Weavers',
    manufacturer: 'Shri Prashant Gaikwad',
    manufacturerId: 'm4',
    price: 42000,
    rating: 4.7,
    reviews: 58,
    material: 'Blended Silk, Zari',
    motif: 'Peacock Eye Border',
    color: 'Royal Blue & Ivory',
    location: 'Aurangabad',
    image: 'https://images.unsplash.com/photo-1618901185975-d59f7091bcfe?w=600&h=800&fit=crop&auto=format',
    badge: 'New Design',
    collection: 'New Arrivals',
  },
  {
    id: 'p6',
    name: 'Triveni Paithani',
    brand: 'Yeola Silk House',
    manufacturer: 'Shri Balkrishna More',
    manufacturerId: 'm6',
    price: 67000,
    rating: 4.8,
    reviews: 74,
    material: 'Pure Tussar Silk, Gold Zari',
    motif: 'Triveni (Three-thread)',
    color: 'Deep Burgundy & Gold',
    location: 'Yeola',
    image: 'https://images.unsplash.com/photo-1664636124899-4a121f1ce449?w=600&h=800&fit=crop&auto=format',
    badge: 'Rare Weave',
    collection: 'Royal Collection',
  },
  {
    id: 'p7',
    name: 'Kalicharan Wedding Paithani',
    brand: 'Royal Paithani House',
    manufacturer: 'Smt. Vaishali Kulkarni',
    manufacturerId: 'm2',
    price: 175000,
    rating: 5.0,
    reviews: 29,
    material: 'Pure Silk, 24K Gold Zari',
    motif: 'Kalicharan (Full Brocade)',
    color: 'Deep Purple & Pure Gold',
    location: 'Paithan',
    image: 'https://images.unsplash.com/photo-1664636126154-7a6ce64edd21?w=600&h=800&fit=crop&auto=format',
    badge: 'Wedding Special',
    collection: 'Wedding Collection',
  },
  {
    id: 'p8',
    name: 'Asawali Heritage Paithani',
    brand: 'Heritage Weaves',
    manufacturer: 'Shri Ramchandra Deshmukh',
    manufacturerId: 'm1',
    price: 95000,
    rating: 4.9,
    reviews: 51,
    material: 'Pure Mulberry Silk, Real Zari',
    motif: 'Asawali (Vine & Flower)',
    color: 'Forest Green & Gold',
    location: 'Nashik',
    image: 'https://images.unsplash.com/photo-1664636125274-743c470f62e6?w=600&h=800&fit=crop&auto=format',
    badge: 'Signature',
    collection: 'Heritage Collection',
  },
];

export function formatPrice(price: number): string {
  if (price >= 100000) {
    return `₹${(price / 100000).toFixed(2)} L`;
  }
  return `₹${price.toLocaleString('en-IN')}`;
}
